replicaCount: 1
image:
  repository: graphprotocol/graph-node
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  annotations: {}
  type: ClusterIP
  metricsPort: 8040
  jsonRpcPort: 8020
  graphqlPort: 8000
  graphqlWsPort: 8001
  indexPort: 8030

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  ipfs: https://api.thegraph.com/ipfs/
  chains:
    fuji:
      providers:
      - label: fuji
        url: https://chain-testnet.actafi.org/ext/bc/C/rpc
        features: [ archive ]

postgres:
  db: node
  host: subgraph.c4mrhzdfel89.us-east-1.rds.amazonaws.com
  replicaHost: subgraph.c4mrhzdfel89.us-east-1.rds.amazonaws.com
  user: postgres
  password:
    fromSecret:
      name: postgresql-staging
      key: password

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 200Mi

blockIngestorNodeId: index_node

role: "query-node"

monitoring:
  enabled: true

# If you are using standalone installation option it could be useful for you to enable ingress to allow your application outside of the cluster connect to query-nodes by graphql.
ingress:
  enabled: true
  hosts:
  - subgraph-test.p2p.finance

# If you are using standalone installation option it could be useful for you to enable ingress to allow your application outside of the cluster connect to query-nodes by graphql websocket.
ingressWebsocket:
  enabled: true
  hosts:
  - subgraph-ws-test.p2p.finance
