
replicaCount: 1
image:
  repository: graphprotocol/graph-node
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  annotations: {}
  type: ClusterIP
  metricsPort: 8040
  jsonRpcPort: 8020
  graphqlPort: 8000
  graphqlWsPort: 8001
  indexPort: 8030

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  ipfs: http://ipfs-staging-ipfs:5001/
  chains:
    fuji:
      providers:
      - label: fuji
        url: https://avalanche-fuji.infura.io/v3/31eb485f02894528b7918805d1f4609a
        features: [ archive ]

postgres:
  db: node
  host: postgresql-staging
  replicaHost: postgresql-staging
  user: postgres
  password:
    fromSecret:
      name: postgresql-staging
      key: password

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi

blockIngestorNodeId: index_node

role: "index-node"

monitoring:
  enabled: true

ingress:
  enabled: false
  annotations: {}
  hosts:
  tls: []

ingressWebsocket:
  enabled: false
  annotations: {}
  hosts:
  tls: []