
replicaCount: 1
image:
  repository: graphprotocol/graph-node
  pullPolicy: IfNotPresent
  tag: "v0.29.0" # v0.24.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  annotations: {}
  type: ClusterIP
  metricsPort: 8040
  jsonRpcPort: 8020
  graphqlPort: 8000
  graphqlWsPort: 8001
  indexPort: 8030

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  ipfs: https://api.thegraph.com/ipfs/
  chains:
    fuji:
      providers:
      - label: fuji
        url: https://chain-testnet.actafi.org/ext/bc/C/rpc
        features: [ archive ]

postgres:
  db: node
  host: subgraph.c4mrhzdfel89.us-east-1.rds.amazonaws.com
  replicaHost: subgraph.c4mrhzdfel89.us-east-1.rds.amazonaws.com
  user: postgres
  password:
    fromSecret:
      name: postgresql-staging
      key: password

resources:
  requests:
    cpu: 250m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 1Gi

blockIngestorNodeId: index_node

role: "index-node"

monitoring:
  enabled: true

ingress:
  enabled: false
  annotations: {}
  hosts:
  tls: []

ingressWebsocket:
  enabled: false
  annotations: {}
  hosts:
  tls: []