replicaCount: 1

image:
  repository: ipfs/go-ipfs
  pullPolicy: IfNotPresent
  tag: ""

command:
  - /usr/local/bin/start_ipfs
  - daemon
args:
  - --migrate=true

service:
  type: ClusterIP

profile: server

ingressApi:
  enabled: false

ingressGateway:
  enabled: false

swarm:
  enabled: false
  type: ClusterIP
  nodePort: ""
resources: {}

persistence:
  enabled: false
  size: "8Gi"
  accessModes:
    - ReadWriteOnce
