helmDefaults:
  wait: true

releases:
- name: postgres
  chart: ../charts/postgres
  labels:
    component: postgres
  values:
  - values/postgres.yaml

- name: graphprotocol-node-index
  chart: ../charts/graphprotocol-node
  labels:
    component: node-index
  values:
  - values/graphprotocol-node-index.yaml
  - config:
      ipfs: "http://ipfs-ipfs:5001/"
  needs:
  - postgres

- name: graphprotocol-node-query
  chart: ../charts/graphprotocol-node
  labels:
    component: node-query
  values:
  - values/graphprotocol-node-query.yaml
  - config:
      ipfs: "http://ipfs-ipfs:5001/"
  needs:
  - postgres

- name: ipfs
  chart: ../charts/ipfs
  labels:
    component: ipfs
  values:
  - values/ipfs.yaml
  - args:
    - --migrate=true
    - --offline