{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}
  labels:
    {{- include "graphprotocol-node.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "graphprotocol-node.fullname" $ }}
                port: 
                  name: graphql
    {{- end }}
{{- end }}
---
{{- if .Values.ingressWebsocket.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}-ws
  labels:
    {{- include "graphprotocol-node.labels" . | nindent 4 }}
  {{- with .Values.ingressWebsocket.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingressWebsocket.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "graphprotocol-node.fullname" $ }}
                port: 
                  name: graphql-ws
    {{- end }}
{{- end }}
